version: '3.8'

services:
  youtube-proxy:
    image: starleydev/youtube-proxy:latest
    container_name: youtube-proxy
    ports:
      - '2536:2536'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
